### ISSUE TITLE
Site Coder button won't work

### ISSUE THREAD

**Issue by Jackkillian** [Jackkillian/JK-Dashboard#2]
### Problem:
When the 'Site Coder' button is pressed, nothing happens.

### OS [Like macOS 10.0.0 or Windows 10]:
macOS Sierra
Version 10.12.6 (16G29)

### Hardware:
MacBook Air (13-inch, Late 2010)
Processor 1.86 GHz Intel Core 2 Duo
Memory 4 GB 1067 MHz DDR3
Graphics NVIDIA GeForce 320M 256 MB

### Python Version
3.7.2

### Python IDE [Like IDLE or PyCharm]:
IDLE
Version 3.7.2
Python Launcher
Version 3.7.2 (3.7.2)

### Error from IDE [Like SyntaxError or ImportError]:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/——————/Desktop/JK Dashboard/JK Dashboard.py", line 138, in <lambda>
    self.but_sitecoder = Button(self, text='Site Coder', command=lambda: SiteCoder.main)
AttributeError: module 'SiteCoder' has no attribute 'main'

Expected behavior [Like a clear and concise description of what you expected to happen]:
Site Coder extension to open.

**Comment by Jackkillian** [comment]
Also, the other button won't work either.
